### ISSUE TITLE
rain_sensor_active attributes not set 

### ISSUE THREAD

**Issue by antro31** [vinteo/hass-opensprinkler#103]
Hi all and thanks for the job for this integration. 
I have expected that "rain_sensor_active" attributes was showing the state of the rain_sensor connected to OpenSprinkler. 
This seems not to be the case. 
Am I missing something? 

thanks,

**Comment by travisghansen** [comment]
It may be sensor 1 or 2...what version of firmware are you on?

**Comment by antro31** [comment]
2.1.9 on open sprinkler
1.0.3 for opensprinkler integration. 

It is not sensor 1 or 2 either. All of my sensors (rain, sensor1 or sensor2) are set to false, whereas GPIO14 (on which is connected the rain sensor) shows that the rain sensor is active. Confirmed by the delay OpenSprinkler is setting)

**Comment by travisghansen** [comment]
Hmm, not sure I follow entirely. The rain_sensor_active datapoint I believe is based on a legacy firmware logic and likely won’t show anything other than none/empty in hass if you’re on 2.1.9 (which moved to sensor 1/2). How do you have it configured if not configured as either sensor 1 or 2?

Forgive the ignorance, I’m new to OS so much of what was programmed was based entirely off the api docs and little to no practical experience.

**Comment by antro31** [comment]
Mm.. I see, then, is there a binary sensor that tells if the rain sensor is active or not?

**Comment by travisghansen** [comment]
Depending on if you have it attached to sensor 1 or 2 there are a bunch of respective datapoints `sensor_x_*`.. have a look at those and see if you can make sense of your situation and if it properly reflects what you think they should be.

**Comment by travisghansen** [comment]
Maybe I misunderstood your question. If you found the correct attribute you can use a template binary sensor and create your own using the attribute(s).

**Comment by antro31** [comment]
The fact is that I don't find the correct attribute. 
None of rain sensor active, sensor 1 active, sensor 2 active or rain sensor enabled gives me the status of the connected rain sensor. 
The closest would be "rain delay active" which is active when a rain delay is set (so likely when rain sensor have been activated). But I would have expected "rain sensor active" to be set to "True" when rain sensor has detected rain. 
Looking at the API, there are 2 different binaries: One for detection of a rain delay, one for sensor activation. 
Anyway, in the meantime, I'll use "rain delay active"

**Comment by vinteo** [comment]
We only provide what the OS API provides. I can't test it myself since I don't have a rain sensor but I believe the `rain_delay_active` sensor is the right one to use for what you want.

I'll close this for now, please reopen if you find otherwise
