### ISSUE TITLE
Component causing unresponsiveness of ha

### ISSUE THREAD

**Issue by dvbit** [vinteo/hass-opensprinkler#105]
Hi I have a 2.5 hw and firmware opensprinkler.
I had to uninstall it because I found it was leading to home assistant stall after about 45 minutes
Python virtual env install on Debian 10.
Intel i7

**Comment by travisghansen** [comment]
Doesn't sound fun. I've got a couple changes to the library and hass integration that may make it better..

**Comment by dvbit** [comment]
Thanks. Let me know when they are rolled in.
Is there some one else having the same issue?.

**Comment by ruimarinho** [comment]
I was troubleshooting this myself and just noticed you've opened this issue @dvbit. I am experiencing exactly the same thing and I've been disabling custom components to do a binary search for a potential candidate.

Luckily, I still have the git pull logs:

```
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 14 (delta 9), reused 13 (delta 9), pack-reused 0
Unpacking objects: 100% (14/14), done.
From https://github.com/vinteo/hass-opensprinkler
   a494020..eb2c6d3  master     -> origin/master
 * [new tag]         v1.0.4     -> v1.0.4
Updating a494020..eb2c6d3
Fast-forward
 README.md                                        | 97 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++----
 custom_components/opensprinkler/__init__.py      | 43 ++++++++++++++++++++++++++++++++++++++++++-
 custom_components/opensprinkler/binary_sensor.py | 18 ++++++++++++------
 custom_components/opensprinkler/const.py         | 18 ++++++++++++++++++
 custom_components/opensprinkler/sensor.py        | 18 ++++++++++++------
 custom_components/opensprinkler/services.yaml    |  2 +-
 custom_components/opensprinkler/switch.py        | 18 ++++++++++++------
 7 files changed, 190 insertions(+), 24 deletions(-)
```

Looking at the commits, I suspect the `SCAN_INTERVAL` issue could have caused the unresponsiveness, but it's too soon to tell in my case. My HASS 'hangs' and automations stop working, but there is nothing in the log files indicating any error scenario.

**Comment by travisghansen** [comment]
You're sure it's from this component? I'm running very few extra components and hass does not become unresponsive (OS does however even outside of hass).

I've opened:

- https://github.com/vinteo/hass-opensprinkler/pull/106
- https://github.com/vinteo/py-opensprinkler/pull/37

The 2 combined should generally make things in a bit better shape but don't know if it'll resolve this issue or not.

**Comment by dvbit** [comment]
I have a lot of components. Maybe it is some conflict with one of them.
I tried to remove opensprinkler since it was the last updated. 
And indeed it is not anymore happening or at least it is slower.

**Comment by dvbit** [comment]
@ruimarinho  i also checked the logs.
I can see some "known errors" i already had.
What is noticeable is that as the system grinds to halt there are more and more async timeouts in the log

**Comment by travisghansen** [comment]
Ok likely something with this integration then...

**Comment by ruimarinho** [comment]
Same behaviour. It looks like something delays the event loop. I can't say for certain it's this component, because the update to master looked like it had fixed it. However, it has returned to the same state now.

I'll disable it and report back.

**Comment by travisghansen** [comment]
Same behavior with what?

**Comment by ruimarinho** [comment]
`2020-06-11 22:51:20 WARNING (MainThread) [custom_components.xxx] Updating xxx took longer than the scheduled update interval 0:02:00`

I see this on multiple custom components after 2-3h of usage.

**Comment by ruimarinho** [comment]
Interestingly, this stated showing up just before I decided t dsiable it:

```
2020-06-11 22:58:12 ERROR (SyncWorker_17) [backoff] Giving up request_http(...) after 3 tries (pyopensprinkler.OpenSprinklerConnectionError: Cannot connect to controller)
2020-06-11 22:58:12 ERROR (MainThread) [custom_components.opensprinkler] Unable to connect to OpenSprinkler controller: Cannot connect to controller```

Although all the entities are updated and functional.

**Comment by travisghansen** [comment]
Is OS ui still available/responsive for you?

**Comment by vinteo** [comment]
@ruimarinho @dvbit Do you guys run automations in HA to run/stop stations? I think you guys have that in common. I have a new theory it could be due to I/O stuff (run / stop) on non async calls degrading performance or locking things up. v1.0.5 has fixes for this issue, please see if the new version helps.

**Comment by travisghansen** [comment]
I think the non async methods are wrapped automatically by hass but that’s just a guess. Will be interesting to see what happens after upgrading to the latest if anything.

**Comment by antro31** [comment]
I all. I do confirm that this integration made ha unresponsive after à while. I got ha stuck from time to time. Having à look at the logs, I have noticed that unresposiveness stars when this integration being unresponsive.
Disabling it went back to normal, even after a long time. 
Hope 1.0.5 will correct the issue. Will try it later on

**Comment by ruimarinho** [comment]
@vinteo I don't... the only automations I have on open sprinkler are related to notifications for now. I can also confirm that disabling this component restores the normal behaviour of HASS. 

Will give 1.0.5 a shot!

**Comment by dvbit** [comment]
@vinteo one but it has been deleted since problems.

**Comment by antro31** [comment]
Hi all. Just gave a try to 1.0.5. 
Sorry to say, but same issue. HA became unresponsive two times. Since I removed opensprinkler integration, no more worries. 
An idea how to fix it?

**Comment by travisghansen** [comment]
Can you try running hass with the following environment variable?

`PYOPENSPRINKLER_SKIP_ALL_ENDPOINT=1`

**Comment by antro31** [comment]
How to do that? (I am on HassOS so little to no control on environment variables for Home Assistant)

**Comment by dvbit** [comment]
I have a python venv installation please advide on how to set the env variable and I will try

**Comment by travisghansen** [comment]
If you have a bash shell you can do `export PYOPENSPRINKLER_SKIP_ALL_ENDPOINT=1` once in the shell and all subsequent commands will inherit the value. If you want to do per-command you can simply invoke commands with that in front..

`PYOPENSPRINKLER_SKIP_ALL_ENDPOINT=1 <command>`

**Comment by dvbit** [comment]
I installed latest.
since a couple of days.
Seems to work and not cause any problems.
No env variable set.
Can be closed for me.
TX

**Comment by sdwilsh** [comment]
It might be worth replacing the use of `httplib2` in `pyopensprinkler` with something that works with `asyncio` as well.  That will allow home assistant to let other things run while the requests are pending.

**Comment by travisghansen** [comment]
@sdwilsh I'm pretty sure the updates happen in an async fashion within the bigger context of hass. In essence, the ecosystem implicitly runs this stuff async even if the underlying library doesn't support async (as is the case with pyopensprinkler).
