### ISSUE TITLE
Homeassistant core crash

### ISSUE THREAD

**Issue by liri** [vinteo/hass-opensprinkler#122]
Hi,
i'm no entirely sure what is the root cause but it started happen after i added opensprinkler custom component so this is the main suspect at the moment.
After a few hours, my homeassistant gets unresponsive and in log i can see this message which right after it the log is starting to be "empty" (no normal messages):
Error fetching OpenSprinkler resource status data: Error fetching OpenSprinkler state

Now, i can say for sure that my opensprinkler device is disconnecting from wifi here and there but it shouldn't be a problem, correct?

is there a chance that the plugin somehow locks DB or causing the homeassistant core (not HASS) to crash?
let me know if i can fetch more information from my setup to help you understand.

thank you,
Liron

**Comment by vinteo** [comment]
Hi @liri, I can confirm that I have been able to reproduce a HA lockup when the wifi connection drops suddenly. I am hoping this will help: https://github.com/vinteo/hass-opensprinkler/pull/123

Would you be able to test it by installing `1.1.0-beta.1` from HACS?

**Comment by liri** [comment]
hi @vinteo, thanks for that!
i can't test HACS unfortunately, do you have a custom component for me to test with?

**Comment by vinteo** [comment]
Yea, install the files from this branch/PR https://github.com/vinteo/hass-opensprinkler/pull/123

**Comment by liri** [comment]
thanks, i copied all files but the integration isn't coming up, did i miss something?

**Comment by vinteo** [comment]
Where did you copy it to? are there any errors in the HA logs?

**Comment by liri** [comment]
copied custom_components/opensprinkler inside custom_components (same as before) and no errors in log, just ignoring the whole thing

**Comment by liri** [comment]
ignore, re-copied the folder and it pop up in integrations again. will update soon.

**Comment by liri** [comment]
i think it's safe to say that the PR solves the issue, I also tried disconnecting the device manually and saw the errors in HA log and after reconnect the device HA recovered.

thank you @vinteo !

**Comment by vinteo** [comment]
Great news and thank you, we will do more testing and try and get it released into the main branch soon.
