### ISSUE TITLE
After Home Assistant 0.81.2 Update- Hass-opensprinkler could not be setup

### ISSUE THREAD

**Issue by hmbarbosa** [vinteo/hass-opensprinkler#13]
Hi,

After updating to Hassio 0.81.2 all entity is not available and I got a notification that Hass-opensprinkler could not be setup..

Are you able please to have a look on you hv a time?

cheers, Beto

**Comment by vinteo** [comment]
hi @hmbarbosa I just pushed an update, can you try it now?

**Comment by hmbarbosa** [comment]
hello @vinteo , all back to normal now. Thank you very much!

**Comment by vinteo** [comment]
Great!
