### ISSUE TITLE
Error when try connect

### ISSUE THREAD

**Issue by pepsonEL** [vinteo/hass-opensprinkler#139]
When i try connect integration with my opensprinkler i recived this error. 
[%key:common::config_flow::error::cannot_connect%]

What i do wrong ?

**Comment by vinteo** [comment]
Need more info, use the same URL you use to get to the opensprinkler UI

**Comment by lymanc** [comment]
Having same issue as pepsonEL above when I use URL:  http://192.168.1.64 which will successfully open the UI of my opensprinkler.

**Comment by vinteo** [comment]
Note the default port for OpenSprinkler unless you have changed it is 8080 so http://192.168.1.64:8080.

Make sure your Home Assistant can connect to the OpenSprinkler device

**Comment by lymanc** [comment]
Thank you for the prompt response.  Previously I had tried port 8080 with no joy.  But good news, your response caused be to explicitly try port 80, and it was successful.  If it is of interest, I am running AppVersion: 2.2.1,  Firmware: 2.1.9(2), and Hardware Version: 3.1-DC.

**Comment by ygreq** [comment]
Port 80 worked for me as well. I do not remember changing it. I run an older version of OpenSprinkler. 

Thank you all!!
