### ISSUE TITLE
Enhancement request: UI

### ISSUE THREAD

**Issue by theOrakle** [vinteo/hass-opensprinkler#14]
Hey Vincent,

First and foremost, love the product.  

I'm wandering if we could make the timer more like a dimmable light.  The time of the zone could still be automated from the entity itself and the UI would only show the timer if you click on the entity.

Just a thought.

**Comment by vinteo** [comment]
I think this will be a custom UI component, I have not looked much into custom UI components (lovelace) yet so not sure if it is possible. 

Happy for someone to give it a go though :)

**Comment by vinteo** [comment]
I think this is out of scope for this integration
