### ISSUE TITLE
Both sensors  are never changed

### ISSUE THREAD

**Issue by eyalsac** [vinteo/hass-opensprinkler#141]
Both sensors: binary_sensor.deviceName_sensor_1_active  and binary_sensor.deviceName_sensor_2_active, are always off. 
In my case the 1st. is flow sensor and the 2nd. is float contact closer.

**Comment by vinteo** [comment]
Hi, 

I have confirmed that we are returning what is given by the OS API correctly. Unfortunately I do not use sensors so I cannot test it in a real life situation.

I am not sure whether the active/inactive makes sense for a flow sensor for example? Are you perhaps wanting to know if it is enabled? This is available as an attribute of the binary sensor ie attribute `deviceName_sensor_1_enabled` of `binary_sensor.deviceName_sensor_1_active`

**Comment by vinteo** [comment]
Will close this for now as I don't think there is a bug here.
