### ISSUE TITLE
Home assistant Integration missing

### ISSUE THREAD

**Issue by mrslvd** [vinteo/hass-opensprinkler#151]
Hello,
I've installed OpenSprinkler from HACS and restart the host (Supervisor->System->Reboot host). But after that I can't find OpenSprinkler Integration from Configuration->Integrations->Add integration. I've checked /config/custom_components/opensprinkler folder and files are there.
What could be the reason?
Best regards,
Miro

**Comment by vinteo** [comment]
anything in the logs?

**Comment by vinteo** [comment]
its probablt the same but usually restart using configuration-> server controls

![image](https://user-images.githubusercontent.com/819711/123340517-acbc6700-d58f-11eb-941e-f815af64d416.png)

**Comment by mrslvd** [comment]
Hello,
Thank you very much for your answer. Actually, let's say 15 minutes later,
I tried to add the integration using the HASS App on Android and the
integration was there.

Best regards,
Miro
