### ISSUE TITLE
Duplicate station names not handled correctly

### ISSUE THREAD

**Issue by klusekb** [vinteo/hass-opensprinkler#153]
I have two OpenSprinkler controllers - one for the front yard and one for the backyard. There are multiple stations defined for each - 3 and 4, respectively. The remaining stations ("S0x") are unused.

I added both controllers to Home Assistant. There were no problems with the first one (front). However, when I added the second one (back), I only saw two stations instead of eight. I figured out that I only saw the two stations with unique names. The stations with names that were also present in "back" (including all the unused "S0x") were not visible. 

I renamed the two stations I cared about, giving them unique names, removed and re-added the controller and the renamed stations are visible now. This makes me think that in a system with multiple sprinkler controllers, duplicate names are not handled properly.

**Comment by vinteo** [comment]
Can you try it with different `Controller Name` when you add the second integration? There might be still clashed with the `entity_id` but HA should create them with `_2`

**Comment by klusekb** [comment]
They've been different from the very beginning:
![os](https://user-images.githubusercontent.com/86543999/123563324-ed230d00-d768-11eb-9216-fadd96cff3d1.JPG)

**Comment by vinteo** [comment]
Are there entities with like `sensor.xxx_station_status` and `sensor.xxx_station_status_2` ?

If not I would have to look into it further

**Comment by klusekb** [comment]
The entities are present:
![stations](https://user-images.githubusercontent.com/86543999/123563689-f2815700-d76a-11eb-9d8f-2159b7f6a1cd.JPG)
...but the stations are only displayed for the "front" controller:
![front](https://user-images.githubusercontent.com/86543999/123563724-1e044180-d76b-11eb-88ee-f5ae42023f46.JPG)
...and not the "back" one:
![back](https://user-images.githubusercontent.com/86543999/123563755-3c6a3d00-d76b-11eb-8c58-28504e8c130e.JPG)

This might be a display-only issue.

**Comment by vinteo** [comment]
Ah ok, this should go into the https://github.com/rianadon/opensprinkler-card repo as it is owned by someone else. please include the screenshots you have when you report it

**Comment by klusekb** [comment]
Will do. Thank you for looking into this!
