### ISSUE TITLE
 [%key:common::config_flow::error::unknown%] 

### ISSUE THREAD

**Issue by malgates** [vinteo/hass-opensprinkler#156]
Hi,

I installed the AddOn using HACS. When I try to connect my OpenSprinklerPi to HA I am asked to input the credentials. Unfortunately it throws this error at me:

 [%key:common::config_flow::error::unknown%] 

Help highly appreciated.

THX

Chris

**Comment by nanosonde** [comment]
This is already discussed here: https://github.com/vinteo/hass-opensprinkler/issues/92

**Comment by nanosonde** [comment]
I have realized that your issue about [%key:common::config_flow::error::unknown%] and not about  [%key:common::config_flow::error::cannot_connect%].

So this seems to be something different.

As I was able to solve my issue with  [%key:common::config_flow::error::unknown%], I would like to ask you if you could check the names of your stations and programs within OpenSprinkler.
Do you also have special characters in it?
During exporting and importing of the OSPi config, it seems to introduce issue in the string encoding. (to be verfied)

**Comment by topshelf510** [comment]
Not sure if it helps but I had the same error and adding the a protocol and port fixed it for me.

**Comment by EdLeckert** [comment]
The cause of the error and the possible solution (such as mentioned in the comment above by @topshelf510) may be made clearer by #244.
