### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by EllisO63** [vinteo/hass-opensprinkler#157]
I've installed the integration via HACS, but there doesn't appear to be anywhere to input the network info etc of my OpenSprinkler/ Both HA and OpenSprinkler are on the same network (ethernet) - can ping both - and both are working

**Comment by Nick-Adams-AU** [comment]
Just confirming that you have restarted HA after installing the integration?

From there, go to Integrations, click "Add integration", search OpenSprinkler and then follow the prompts. Let me know where this falls over.

**Comment by EllisO63** [comment]
Hi Nick

Sorry, first bit was entirely my fault, RTFM as they say. However, I’m now getting this



Ellis Organ

**Comment by Nick-Adams-AU** [comment]
Sorry, I'm not seeing any attachment or image. Are you able to upload it via the website instead of by email?

**Comment by EllisO63** [comment]
Nick 

Found the error - the port for the connection to the OpenSprinkler is 80 when connected via Ethernet, not 8080 (Wi-Fi)

Many thanks

Ellis Organ
