### ISSUE TITLE
Rain Delay

### ISSUE THREAD

**Issue by mstarks01** [vinteo/hass-opensprinkler#158]
First, thank you for this integration. I enjoy both Home Assistant and OpenSprinkler, so I was very happy to see this.

I'd like to request a toggle for rain delay on/off. I know it's not a simple binary in OpenSprinkler, but maybe setting something like `99999999 days` as a value could effectively serve this purpose. This would allow for toggling water or not at the global level.

**Comment by vinteo** [comment]
There was a plan to do a service to set the water level https://github.com/vinteo/hass-opensprinkler/issues/101 so many a better alternative is to have that and set the water level to 0

**Comment by dodgydino** [comment]
Sorry to bump this thread, but a 'set rain delay' service would be great.

In my use case, I've configured my opensprinkler to change water level using the Zimmerman method, meaning it will change water level based on past weather conditions without my input. As that method is only reactive (ie it will lower the water level after a rain event), the issue for me would be that if I pre-emptively set the water level to '0' as a pseudo rain delay, it's possible that Opensprinkler could change it back on its own, defeating the workaround rain delay.

I'd be looking to use a 'set rain delay' service using an Automation based on two triggers: 1st - predicted rain above a %,  and 2nd - actual recorded rain.

**Comment by vinteo** [comment]
This was already done by a helpful contributor, check the readme for an
example

**Comment by vinteo** [comment]
Fixed in #174

**Comment by vinteo** [comment]
Sorry I got confused

**Comment by vinteo** [comment]
I took another look at the opensprinkler API and like the original comment said there is no toggle for the rain delay. In your case you will need a service to set the water level adjustment to `manual`. And set it back after

**Comment by dodgydino** [comment]
Appreciate you looking into it. Actually, your comment on the API led me to finding the API document (didn't even think to look before), which describes using HTTP GET commands to change variables. Rain delay can be set by sending the number of hours you want it for. I've now been able to create an automation using the REST Notify service to set the rain delay, without needing to change the water level.

**Comment by vinteo** [comment]
Looking to do a service for rain delay: https://github.com/vinteo/hass-opensprinkler/issues/251

**Comment by vinteo** [comment]
Rain delay service done in v1.2.6
