### ISSUE TITLE
After update 0.88 Hass-opensprinkler not working

### ISSUE THREAD

**Issue by hmbarbosa** [vinteo/hass-opensprinkler#16]
Hello Dear,

When you have a spare time are you able please to have a look at the problem after the latest hassio update?

Not loading anymore.

Log Details (WARNING)
Thu Feb 21 2019 19:34:31 GMT+1100 (Australian Eastern Daylight Time)

Integrations need to be in their own folder. Change binary_sensor/hass_opensprinkler.py to hass_opensprinkler/binary_sensor.py. This will stop working soon.

Cheers
Humberto

**Comment by vinteo** [comment]
Yes I saw the breaking change in the release notes, but I am on holiday
overseas right now, I will try to get to it this weekend.

**Comment by hmbarbosa** [comment]
Thnanks! and Have a nice holiday mate.

**Comment by madrose** [comment]
that would be awesome

**Comment by vinteo** [comment]
I have pushed an update, you will need to remove all the previous `hass_opensprinkler.py` files from the `custom_components` folder and just add the new `hass_opensprinkler` folder there

**Comment by hmbarbosa** [comment]
Awesome mate! Thanks!!! Just one thing when downloaded/clone the folder name is extracted as "hass-opensprinkler" instead of hass_opensprinkler 

working all good so far...

Obrigado/Thanks
Berto

**Comment by vinteo** [comment]
thanks, renamed the folder!

**Comment by vinteo** [comment]
closing this now, if any issues please create a new issue
