### ISSUE TITLE
Station switch - running time

### ISSUE THREAD

**Issue by Luty-tech** [vinteo/hass-opensprinkler#162]
i can set up maximum run time with manual station switch around 12h, can i make on off switch without time or set up runing time over 20h? 
here is my configuration.yaml entry:

switch:
  - platform: template
    switches:
      lampki_swiateczne:
        value_template: "{{ is_state('binary_sensor.oswietlenie_4_station_running', 'on') }}"
        turn_on:
          service: opensprinkler.run
          data:
            entity_id: binary_sensor.oswietlenie_4_station_running
            run_seconds: 370000
        turn_off:
           service: opensprinkler.stop
           data:
            entity_id: binary_sensor.oswietlenie_4_station_running

**Comment by vinteo** [comment]
The maximum Opensprinkler can handle is 18 hours (64800 seconds)
