### ISSUE TITLE
change url

### ISSUE THREAD

**Issue by mac-city** [vinteo/hass-opensprinkler#163]
is it possible to change the url on my up and running setup?  I changed wifi and ip address and just want to change it without having to delete the integration and probably losing the setup.  love this integration!  thanks!

**Comment by vinteo** [comment]
no, I don't think it is possible

**Comment by mac-city** [comment]
bummer

**Comment by travisghansen** [comment]
You can hack the file in the storage dir pretty easy yeah. Just shut down ha, edit the file, and restart.

**Comment by mac-city** [comment]
oh shoot, I just removed, reinstalled.  this has come up on other integrations so let me see if I can find it for future reference, thanks!  so I would have to ssh to get there?  where is the storage directory.  I don't think I get get to it if ha is off?  I am running home assistant on proxmox.  the only way I know how to shut down ha is to turn the machine off, and then I couldn't get to that?

**Comment by travisghansen** [comment]
I'm not sure about how to get there in the os. The file you're looking for is `<config dir>/.storage/core.config_entries`
