### ISSUE TITLE
Unable to install package pyopensprinkler==0.7.1

### ISSUE THREAD

**Issue by jjanderson** [vinteo/hass-opensprinkler#166]
Hi,

After upgrading to 2022.3.1

I get this error:

Unable to install package pyopensprinkler==0.7.1: ERROR: Cannot install pyopensprinkler==0.7.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by vinteo** [comment]
v1.1.8 should be available and will fix this

**Comment by jjanderson** [comment]
awesome!

Thanks

**Comment by vinteo** [comment]
It is already released, I have it installed through HACS

**Comment by bjhiltbrand** [comment]
V1.1.7 is the release that I show on github as the latest, as well as what I see in HACS. I also noticed that this issue (https://github.com/vinteo/hass-opensprinkler/issues/169) was opened and then closed in the last day saying they only see V1.1.7

**Comment by vinteo** [comment]
That was super weird, I am pretty sure I did a release. I tried to add it again and it said it is already there, so i just clicked update and it appeared in github. Do you see it now?

**Comment by bjhiltbrand** [comment]
Weird... Yeah, both Github and HACS now show the releases there, and github even says it was released 14 days ago. IDK...
