### ISSUE TITLE
Zones / Programs shown as "Disabled"

### ISSUE THREAD

**Issue by shagadeli** [vinteo/hass-opensprinkler#183]
Hi,

I'd like to use the integration to start and stop programs or zones, but they all show as disabled even if they are enabled on the toggle. 
The stations should be shown as Idle. 

Can someone point me what I'm doing wrong here?

![Screenshot_20220902-154850_Home Assistant](https://user-images.githubusercontent.com/98832261/188176350-50f4cae5-4f46-424f-bf84-c07610dcc119.jpg)

**Comment by vinteo** [comment]
Can you show your config for your IU there

**Comment by shagadeli** [comment]
You mean this?
![Screenshot_20220902-233232_Home Assistant](https://user-images.githubusercontent.com/98832261/188243021-314694de-0ef9-48a9-be1d-efa3aa9cfa0a.jpg)

Or something not card related?

**Comment by vinteo** [comment]
Yea I think this might be card related
