### ISSUE TITLE
Increase Water Level Max Value from 100 to 250

### ISSUE THREAD

**Issue by lnxsrt** [vinteo/hass-opensprinkler#187]
As the integration is currently written, the max of the set_water_level service call is 100%. The max allowable water level in OpenSprinkler is 250%. There are many instances where water levels should be well above the base watering level (hot clear windy summer days). I manually increased 100 to 250 in `const.py` and `services.yaml` and have confirmed that OpenSprinkler has no problem accepting values up to 250.

**Comment by vinteo** [comment]
If you could open a pull request for that, would be great.

**Comment by lnxsrt** [comment]
Opened a PR on it. #194
