### ISSUE TITLE
Cant load opensprinkler after 2022.11 update of HA

### ISSUE THREAD

**Issue by coldkevin** [vinteo/hass-opensprinkler#193]
After updating to the newest HA release, Im left with openspirnkler unable to 

Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 3:38:29 PM (3 occurrences)
Last logged: 3:38:35 PM

Unable to install package pyopensprinkler==0.7.3: ERROR: Cannot install pyopensprinkler==0.7.3 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.2.1 -> 22.3 [notice] To update, run: pip install --upgrade pip

Logger: homeassistant.setup
Source: setup.py:184
First occurred: 3:38:35 PM (1 occurrences)
Last logged: 3:38:35 PM

Setup failed for custom integration opensprinkler: Requirements for opensprinkler not found: ['pyopensprinkler==0.7.3'].

**Comment by kerhbal** [comment]
same here

**Comment by vschild** [comment]
same here

**Comment by vinteo** [comment]
please try the latest release

**Comment by spikeygg** [comment]
The latest release of 1.1.11 works! Thanks @vinteo!

**Comment by locomite** [comment]
yep, all working now for me too

**Comment by coldkevin** [comment]
All good now! Appreciate the fast response and fix!

**Comment by kerhbal** [comment]
works now!

**Comment by KunZhaoChristchurch** [comment]
still does not work :(

**Comment by vinteo** [comment]
HA Core needs to be 2022.11 and OpenSprinkler intration v1.1.11
