### ISSUE TITLE
Dependencies errors in v1.1.12

### ISSUE THREAD

**Issue by PKort** [vinteo/hass-opensprinkler#196]
After upgrading from v1.1.10 to v1.1.12 integration stopped working. Following error was thrown:

Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 11 November 2022 09:28:27 (3 occurrences)
Last logged: 11 November 2022 09:28:38
Unable to install package pyopensprinkler==0.7.4: ERROR: Cannot install pyopensprinkler==0.7.4 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by mrwildbob** [comment]
Where can I download version 1.1.10?  I cant seem to find it.

**Comment by vinteo** [comment]
Either use HACS you it will be under releases: https://github.com/vinteo/hass-opensprinkler/releases
