### ISSUE TITLE
After HA update 2022.12 Opensprinkler does not work

### ISSUE THREAD

**Issue by RobHomey** [vinteo/hass-opensprinkler#199]
After upgrade to HA 2022.12 Opensprinkler is not working anymore. I get the following error:

Logger: homeassistant.util.package
Source: util/package.py:98 
First occurred: 7 december 2022 om 23:47:09 (3 occurrences) 
Last logged: 7 december 2022 om 23:47:35

Unable to install package pyopensprinkler==0.7.4: ERROR: Cannot install pyopensprinkler==0.7.4 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 22.3.1 [notice] To update, run: pip install --upgrade pip

**Comment by JurajNyiri** [comment]
Same here, revert to previous version 2021.11.05 worked.

**Comment by vinteo** [comment]
Yes sorry I released 1.1.13 which should work, got distracted and forgot to mention it here.
