### ISSUE TITLE
Not loading after upgrade to 0.75

### ISSUE THREAD

**Issue by FrankSchoene** [vinteo/hass-opensprinkler#201]
Logger: homeassistant.setup
Source: setup.py:184
First occurred: 11:37:26 (1 occurrences)
Last logged: 11:37:26

Setup failed for custom integration opensprinkler: Requirements for opensprinkler not found: ['pyopensprinkler==0.7.5'].

Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 11:36:59 (3 occurrences)
Last logged: 11:37:26

Unable to install package pyopensprinkler==0.7.5: ERROR: Cannot install pyopensprinkler==0.7.5 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.2.1 -> 22.3.1 [notice] To update, run: pip install --upgrade pip

**Comment by vinteo** [comment]
update HASS to 2022.12
