### ISSUE TITLE
Add a licence

### ISSUE THREAD

**Issue by davidjb** [vinteo/hass-opensprinkler#21]
Thanks for making this HA component available, it's really useful.

I just noticed there's no licence present in the repository so would you be able please to add one?  Without a licence, contributing to your code isn't allowed nor is copying/reusing etc (read more at https://choosealicense.com/no-permission/).

If you don't have a licence in mind, I'd suggest the simple and permissive MIT licence (https://choosealicense.com/licenses/mit/), otherwise GitHub maintains https://choosealicense.com/ with list of suggestions depending on requirements.  GitHub also has a [help article](https://help.github.com/en/articles/adding-a-license-to-a-repository) for adding licences via templates or otherwise general details on [licensing a repository](https://help.github.com/en/articles/licensing-a-repository).

Thanks!

**Comment by vinteo** [comment]
Thanks for the suggestion, added.

**Comment by davidjb** [comment]
Thanks very much!
