### ISSUE TITLE
Integration will not work after update to HA 2023.3.0b0

### ISSUE THREAD

**Issue by Bascht74** [vinteo/hass-opensprinkler#210]
Setup failed for custom integration opensprinkler: Requirements for opensprinkler not found: ['pyopensprinkler==0.7.4'].

11:30:41 PM – (ERROR) setup.py - message first occurred at 11:29:53 PM and shows up 2 times
Unable to install package pyopensprinkler==0.7.4: ERROR: Cannot install pyopensprinkler==0.7.4 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip
1

Logger: homeassistant.setup
Source: setup.py:205
First occurred: 11:29:53 PM (2 occurrences)
Last logged: 11:30:41 PM

Setup failed for custom integration opensprinkler: Requirements for opensprinkler not found: ['pyopensprinkler==0.7.4'].

1:30:41 PM – (ERROR) util/package.py - message first occurred at 11:29:48 PM and shows up 6 times

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 11:29:48 PM (6 occurrences)
Last logged: 11:30:41 PM

Unable to install package pyopensprinkler==0.7.4: ERROR: Cannot install pyopensprinkler==0.7.4 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip
Unable to install package music-assistant==1.8.7.4: ERROR: Cannot install music-assistant because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

**Comment by tjorim** [comment]
aiohttp was bumped to 3.8.4 in HA core
Opened a pull request: https://github.com/vinteo/py-opensprinkler/pull/71

**Comment by Kawobei** [comment]
That looks like its completed now what do we do? HACS doesn't give me an update for it.

**Comment by tjorim** [comment]
Now the maintainer @vinteo should merge the PR above and create a new release. (Also note this update will not work on older HA versions because of dependencies)

**Comment by vinteo** [comment]
will only do a release when 2023.3 is released

**Comment by tjorim** [comment]
You can already merge it without creating a new release so beta testers can pull in the master branch. (I also updated the PR to bump the minimum HA requirement, so HACS will not provide the new update to older installs on release anyway).

**Comment by vinteo** [comment]
yea will merge but not release. I noticed that HACS does not enforce the HA requirement in the past but maybe they fixed it,
