### ISSUE TITLE
Not working after update HA to 2023.3

### ISSUE THREAD

**Issue by vschild** [vinteo/hass-opensprinkler#213]
HA says invalid config and the logs show:
`Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 17:51:10 (6 occurrences)
Last logged: 17:52:39

Unable to install package pyopensprinkler==0.7.4: ERROR: Cannot install pyopensprinkler==0.7.4 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip
Unable to install package music-assistant==1.8.7.4: ERROR: Cannot install music-assistant because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip`

**Comment by wokkeltje13** [comment]
Same issue

**Comment by vinteo** [comment]
Update to 1.1.15

**Comment by vschild** [comment]
Thanks! Now working!
