### ISSUE TITLE
unable to connect Open Sprinkler controller since update OS

### ISSUE THREAD

**Issue by spainpiio** [vinteo/hass-opensprinkler#215]
Since  updating to OS 2.2.0 (1)

I get this message:
[%key:common::config_flow::error::unknown%]
![image](https://user-images.githubusercontent.com/104723408/229279006-96a7b054-72b7-4054-bd11-05391d09e513.png)

**Comment by vinteo** [comment]
I haven't tested it yet but according to be docs the API should not be a
breaking change. But upgrading does do a factory reset on your device, so
have you setup the device to exactly what it was again?

**Comment by spainpiio** [comment]
Yes, and I can open the dashboard of OS in my browser.
mqtt is working too.

**Comment by spainpiio** [comment]
I changed the pw, but it did not help.
I allready deinstalled OS in  HACS, reboot raspberry,....

![image](https://user-images.githubusercontent.com/104723408/229345320-36c1541e-cd2a-47d6-bcd4-46567b94bab5.png)

**Comment by vinteo** [comment]
I just:

1. Export current OS settings to file.
2. Updated firmware from 2.19 (4) 5o 2.20 (1)
3. Re-setup Wifi settings on device
4. Restore OS settings from file
5. Reset password to previously used password
6. Restarted Home Assistant

And the integration works fine, I can run the stations

**Comment by spainpiio** [comment]
Thank You for testing and confirming that my problem is not related tu the firmware update of OS
I will keep searching.

**Comment by pit65535** [comment]
Unfortunately I got exact the same Problem after upgrading OpenSprinkler to ver. 2.2.0(1). I did what you wrote and still cannot connect to OpenSprinkler. I already uninstalled hass-opensprinkler via hacs rebooted and reinstalled, it still doesn´t work. After trying to connect to OpenSprinkler I found the following in the logs:
Logger: custom_components.opensprinkler.config_flow
Source: helpers/aiohttp_client.py:67
Integration: OpenSprinkler (documentation, issues)
First occurred: 21:11:16 (2 occurrences)
Last logged: 21:16:18

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/opensprinkler/config_flow.py", line 44, in async_step_user
    await controller.refresh()
  File "/usr/local/lib/python3.10/site-packages/pyopensprinkler/__init__.py", line 218, in refresh
    await self._refresh_state()
  File "/usr/local/lib/python3.10/site-packages/pyopensprinkler/__init__.py", line 237, in _refresh_state
    content = await self.request("/ja")
  File "/usr/local/lib/python3.10/site-packages/pyopensprinkler/__init__.py", line 145, in request
    content = await self._request_http(url)
  File "/usr/local/lib/python3.10/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyopensprinkler/__init__.py", line 191, in _request_http
    content = await resp.json(
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 67, in json
    return await super().json(*args, loads=loads, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1120, in json
    return loads(stripped.decode(encoding))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 1545: invalid continuation byte


I really would be happy for any help as i used this integration for a long time and I have a lot oft automations in hass that use it....

**Comment by spainpiio** [comment]
I still have the problem.

**Comment by pit65535** [comment]
I found the problem:
This error occurrs if you have a Program or water-circuit with some umlauts (ie ä,ö,ü or something like this). I noticed OpenSprinkler doesn´t show these letters right in the Web-Interface an so I changed ä to ae and so on, after this I tried again to connect hass-opensprinkler to my OpenSprinkler-Pi and it worked.
I think the problem really comes from the new OpenSprinkler-Software which has a problem showing these coutry-specific letters.

**Comment by spainpiio** [comment]
Hello thank you for your feedback. I had "Umlaute" too, changed it and it did not help in my case.
![image](https://user-images.githubusercontent.com/104723408/233075936-9c926f70-06ff-4689-bd80-1d960f21a60d.png)

**Comment by KlausHans** [comment]
I had the same problem and the issue was indeed some character format for umlauts after importing the settings. The umlauts were only displayed as some unknown ?-char. After replacing them with umlauts again it works. No need to use oe, ae and ue for me. But thanks for the hint in the right direction.

**Comment by spainpiio** [comment]
I just wanted to reset my OS in the hope that I can integrate it again.
A last attempt before that was successful.
