### ISSUE TITLE
Manual Control of OpenSprinkler Switching in Home Assistant

### ISSUE THREAD

**Issue by jbsumme** [vinteo/hass-opensprinkler#217]
I've integrated OpenSprinkler with Home Assistant using the device HAC. I'm able to switch stations on and off using Automations. But when I attempt to turn any of the same switch entities on or off manually nothing happens. In the attached you can see that the Courtyard Station is manually switched on, but the status indicates that the sprinkler valve remains Off. When I run an automation to turn on the same Courtyard Station, the status changes to On and the sprinkler indeed turns on.

[HA Dashboard.pdf](https://github.com/vinteo/hass-opensprinkler/files/11670937/HA.Dashboard.pdf)

**Comment by vinteo** [comment]
Are you able to show the config for the switch? The "enabled" entity enables/disables the station, not run the station. I am not sure if it is up to date as I have not messed with the newer versions of HA but take a look at the example in the README here: https://github.com/vinteo/hass-opensprinkler#creating-a-station-switch

**Comment by jbsumme** [comment]
That's what I thought as well, but the "enabled" entity is what I use in turning the switch on in Automations. Here's an example:
![image](https://github.com/vinteo/hass-opensprinkler/assets/132500718/6101d7f6-5eb4-4529-9d3d-fc9df8effd8f)

**Comment by jbsumme** [comment]
Another thing I noticed is when I add the entity to the Dashboard, this error message appears:
![image](https://github.com/vinteo/hass-opensprinkler/assets/132500718/f6dec972-e0e6-46ee-8c63-01ab8a5db680)

**Comment by vinteo** [comment]
That's running a "service" on the entity which is different. The service will work on almost any entity of the station. Please take a look at the example I linked earlier on how to do a switch.

> Another thing I noticed is when I add the entity to the Dashboard, this error message appears: ![image](https://user-images.githubusercontent.com/132500718/243864256-f6dec972-e0e6-46ee-8c63-01ab8a5db680.png)

There is no `switch` entity because of how the integration works.

**Comment by jbsumme** [comment]
I see it now. I'll give that a try.

**Comment by hankys** [comment]
> Are you able to show the config for the switch? The "enabled" entity enables/disables the station, not run the station. I am not sure if it is up to date as I have not messed with the newer versions of HA but take a look at the example in the README here: https://github.com/vinteo/hass-opensprinkler#creating-a-station-switch

Hi !
I tried to copy the example for the switch to my configuration.yaml to test it, but brings me error. Any ideas ?

![Unbenannt](https://github.com/vinteo/hass-opensprinkler/assets/96357723/d73c646e-688d-4cf1-a4d8-c5a564d40b51)

**Comment by vinteo** [comment]
I tried it and it worked for me, where is it showing that error? Is it from your IDE?

You could try add the input number part through the HA UI instead. Remove the input_number part and use:

![image](https://github.com/vinteo/hass-opensprinkler/assets/819711/6d32c4eb-ae56-44f9-bf75-f91e8e74b9ac)

Then:

![image](https://github.com/vinteo/hass-opensprinkler/assets/819711/5d12861c-d7b8-45f4-a7ca-dc7c53d3c331)

**Comment by hankys** [comment]
Thanks for the quick reply !

There must have been a problem with the copy/paste. First i used the top right button to copy the code for configuration.yaml:

![Unbenannt2](https://github.com/vinteo/hass-opensprinkler/assets/96357723/7a18eec8-e50d-4eb4-8c4c-77b2bbd693cf)

This resultet in the mentioned error when i edited configuration.yaml in Studio code server.


I deleted all the yaml code and copied it again, but now by marking the text in your example. After that it worked without showing any errors.
Don't ask me why......the code looks exactly the same in the editor.....

Thanks for your help anyway ;)
