### ISSUE TITLE
New pause feature

### ISSUE THREAD

**Issue by Hootie81** [vinteo/hass-opensprinkler#218]
Last week there was a new version of opensprinkler firmware released, it includes a pause feature, and also setting start and end dates to programs. it also includes a change so if a station is stopped, the remaining stations can be moved forward instead of having to wait for the additional time to pass for the stopped station.

this pause feature I have been eagerly awaiting since I first jumped in the shower with the sprinklers running! to make use of it I really would like to have an automation that pauses the sprinklers when the bathroom is occupied, any chance of adding a service to the integration?

**Comment by vinteo** [comment]
Definitely something I or some one can add. NO promises on timeframe though

**Comment by vinteo** [comment]
available in v1.2.7
