### ISSUE TITLE
custom_updater version inconsistency

### ISSUE THREAD

**Issue by benvanmierloo** [vinteo/hass-opensprinkler#23]
In hass_opensprinkler/__init__.py, there is:
`VERSION = '0.1.0'`

while in custom_components.json there is:
```
        "version": "0.1.1",
        "local_location": "/custom_components/hass_opensprinkler/__init__.py",
        "remote_location": "https://raw.githubusercontent.com/vinteo/hass-opensprinkler/master/hass_opensprinkler/__init__.py",
```

I think this makes the custom_updater component think the version is out of date.
<img width="486" alt="Screenshot 2019-05-19 at 13 57 28" src="https://user-images.githubusercontent.com/3785514/57981905-2c38ed00-7a3e-11e9-998f-837a533ded76.png">

**Comment by vinteo** [comment]
sorry will get this fixed
