### ISSUE TITLE
Not loading after upgrade of Hass OS

### ISSUE THREAD

**Issue by jjfs127** [vinteo/hass-opensprinkler#233]
![image](https://github.com/vinteo/hass-opensprinkler/assets/79122012/b20ae343-eaf9-4a73-969e-1954c6cba8e5)

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: July 22, 2023 at 11:00:44 PM (3 occurrences)
Last logged: July 22, 2023 at 11:01:19 PM
Unable to install package pyopensprinkler==0.7.6: ERROR: Cannot install pyopensprinkler==0.7.6 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.1.2 -> 23.2.1 [notice] To update, run: pip install --upgrade pip

**Comment by vinteo** [comment]
Please upgrade to the latest version 1.1.17
