### ISSUE TITLE
Getting 504 error when adding integration

### ISSUE THREAD

**Issue by erahhal** [vinteo/hass-opensprinkler#245]
I added the integration through HACS, and when I click the "Add Integratoin" button and add OpenSprinkler, it hangs for a while, then pops up the following error:

```
 Config flow could not be loaded: <html><body><h1>504 Gateway Time-out</h1> The server didn't respond in time. </body></html> 
```

Using Home Assistant on a Raspeberry Pi:

Home Assistant 2023.8.4
Supervisor 2023.08.1
Operating System 10.5
Frontend 20230802.1 - latest

**Comment by EdLeckert** [comment]
This is a network error. I've never encountered it, but:

> 504 Gateway Timeout server error response code indicates that the server, while acting as a gateway or proxy, did not get a response in time from the upstream server that it needed in order to complete the request. A Gateway might refer to different things in networking and a 504 error is usually not something you can fix, but requires a fix by the web server or the proxies you are trying to get access through.

Have you tried communicating with the OpenSprinkler controller via the web interface, from perhaps a laptop at the same point in the network as your RPi? Have you tried pinging the controller from the HA terminal interface, e.g., through the **Terminal & SSH** Add-on? I would expect the same error from those methods.

**Comment by erahhal** [comment]
Sorry i should have been more clear. This happens before I even enter the IP for the device. I have no idea what it's trying to connect to.  I just select the opensprinkler integration and this happens before any config dialog pops up.

**Comment by EdLeckert** [comment]
I don't see many references to this type of problem except this post from over a year ago, [here](https://community.home-assistant.io/t/401960).

Unfortunately, no one responded with a solution. However, it appears that it might not be exclusive to OpenSprinkler.

Are you able to get to the config dialog of other integrations? Just pick something at random and abort.

Is there anything related in the logs besides what you provided earlier?

**Comment by erahhal** [comment]
I tried other integrations, and config option dialogs come up with no problem.  I've got over 30 integrations running without an issue.

Here's exactly what I see:

I click ADD INTEGRATION:

![image](https://github.com/vinteo/hass-opensprinkler/assets/1174130/84861670-039c-40af-94ab-d4bbdabaf489)

Then I filter and click "OpenSprinkler":

![image](https://github.com/vinteo/hass-opensprinkler/assets/1174130/2d421143-34c1-4c14-8224-b3beab76aac2)


Then I see this, which spins for maybe 30 seconds:

![image](https://github.com/vinteo/hass-opensprinkler/assets/1174130/4950807e-6a75-4ca6-8daf-b28dccf258fd)

After which I see this:

![image](https://github.com/vinteo/hass-opensprinkler/assets/1174130/823b97f0-7743-4401-ac67-1f2d831a9a66)

I checked the logs and don't see anything related.

I can confirm that opensprinkler is available on my network from the browser:

![image](https://github.com/vinteo/hass-opensprinkler/assets/1174130/2d7758f0-81a4-4e4d-bd85-8af7c09e1679)

And that the IP is also accessible from the HA box:

![image](https://github.com/vinteo/hass-opensprinkler/assets/1174130/493f00d7-a9cd-4c62-a07c-49fb48804c67)

**Comment by erahhal** [comment]
What could it possibly be trying to connect to before I've configured anything?

**Comment by vinteo** [comment]
How are you accessing Home Assistant itself? Is it through a proxy? If you are, could you try going directly to the local address http://...:8123 and see if you have the same issue?

Have you tried uninstalling the OS integration and reinstalling it again (and restarting HA)? Might be worth a try.

**Comment by vinteo** [comment]
Not the exact issue but for a similar issue in the past: https://community.home-assistant.io/t/hacs-installing-problem-via-integration-error-config-flow-could-not-be-loaded/314501/20

Some people report success in disabling GoogleCast integration. Maybe not GoogleCast but perhaps another integration could be interfering? Any clues in the logs?

**Comment by erahhal** [comment]
No GoogleCast integration installed.  Nothing in the logs.

Tried the http vs https suggestion, and it took much longer to eventually error.  This time though it was just "Error: Unknown".

**Comment by vinteo** [comment]
any luck in uninstalling/reinstalling the integration?

**Comment by erahhal** [comment]
That fixed it!   Must have been in a corrupted state.  Thanks for your help @vinteo !
