### ISSUE TITLE
Integration calls 'OpenSprinkler Current Time changed to xxxx' Infinite Loop every 5 seconds

### ISSUE THREAD

**Issue by johnny-co** [vinteo/hass-opensprinkler#249]
Reviewing the HomeAssistant Logbook in device details for my OSPI OpenSprinkler (Firmware 2.2.0 (2)) a call is being made to set current time every 5 seconds indefinitely.

OpenSprinkler Current Time changed to September 20, 2023 at 8:54 AM
8:54:23 AM - 1 second ago
OpenSprinkler Current Time changed to September 20, 2023 at 8:54 AM
8:54:18 AM - 6 seconds ago
OpenSprinkler Current Time changed to September 20, 2023 at 8:54 AM
8:54:13 AM - 11 seconds ago
OpenSprinkler Current Time changed to September 20, 2023 at 8:54 AM
8:54:08 AM - 16 seconds ago

**Comment by EdLeckert** [comment]
Yes, it is a bit chatty, as the integration refreshes every 5 seconds.

While we work on a better solution you can disable the entity. Go to Settings\Devices & Services\OpenSprinkler, click on the device. Under the `Sensors` section click on `Current Time`, click on the gear icon, turn off `Enabled` and click Update. The entity will no longer be tracked.

**Comment by johnny-co** [comment]
Thank you that worked.

**Comment by vinteo** [comment]
Entity is disabled by default in v1.2.1.
