### ISSUE TITLE
After core update opensprinkler failed to load

### ISSUE THREAD

**Issue by AdrianStanciu22** [vinteo/hass-opensprinkler#261]
After core update from 2023.10.1 to 2023.10.2 integration failed to load.

Logger: homeassistant.setup
Source: setup.py:185
First occurred: 7:03:16 AM (1 occurrences)
Last logged: 7:03:16 AM

Setup failed for custom integration opensprinkler: Requirements for opensprinkler not found: ['pyopensprinkler==0.7.7'].

Logger: homeassistant.util.package
Source: util/package.py:108
First occurred: 7:02:40 AM (3 occurrences)
Last logged: 7:03:16 AM

Unable to install package pyopensprinkler==0.7.7: ERROR: Cannot install pyopensprinkler==0.7.7 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by vinteo** [comment]
please update to v1.2.3

**Comment by AdrianStanciu22** [comment]
Hello!

Please, what should I update to v1.2.3?
Tks

Oct 13, 2023 07:54:37 Vincent Teo ***@***.***>:

**Comment by vinteo** [comment]
The Opensprinkler Integration

**Comment by AdrianStanciu22** [comment]
It is blocked...I dont know how to update, I try to remove and then reinstall it but it can be removed...refuse to be deleted.
However, thank you!

Oct 13, 2023 08:13:37 Vincent Teo ***@***.***>:

**Comment by AdrianStanciu22** [comment]
Updated & works.
