### ISSUE TITLE
Calling Service fails

### ISSUE THREAD

**Issue by qvqn** [vinteo/hass-opensprinkler#278]
Not sure if it's my install but getting failure errors since going to 2024.2

My automation fails, so I tried to call the service and I get this error

![image](https://github.com/vinteo/hass-opensprinkler/assets/14333303/ef57b056-a134-45d2-bdf7-66f76af68290)

![image](https://github.com/vinteo/hass-opensprinkler/assets/14333303/a787b1fb-bbd0-47c6-b030-0c2aba84852e)

**Comment by curlydingo** [comment]
Ahh here it is. I know what this is, it came up in a PR I raised a while ago but we didn’t know what release it would hit us in. I should be able to fix in the next day or two.

**Comment by qvqn** [comment]
glad you are aware of it, was confused no one raised it since 2024.2 has been released for a bit.

I use the call service as my ha is internet exposed and not my ospi so I can manually turn on stations via 4G to check leaks/blockages when I'm out of wifi range.

**Comment by curlydingo** [comment]
Yeah I hadn’t applied the 2024.2 update for a while after it was released :)

I think a lot of people are in a similar situation to you with their ospi
not being online so am keen to get the fox out ASAP.

**Comment by vinteo** [comment]
Should be fixed in 1.3.0

**Comment by qvqn** [comment]
thank you very much for the update
