### ISSUE TITLE
Inappropriate entities listed when configuring services

### ISSUE THREAD

**Issue by EdLeckert** [vinteo/hass-opensprinkler#280]
When using the `Developer tools\SERVICES` interface to learn about and test `OpenSprinkler` services, the user is presented with a confusing and usually inappropriate list of choices of entities that each service can utilize. The same applies in other locations in the UI, such as when using the `Automation Editor` to create a new automation.

The UI should present the user with only valid choices of entities when configuring an `OpenSprinkler` service.

**Comment by vinteo** [comment]
fixed in #281
