### ISSUE TITLE
Issues setting up component

### ISSUE THREAD

**Issue by danielromney** [vinteo/hass-opensprinkler#29]
I am getting the following error. (I am not running HASS.io, I am running HomeAssistant on Rasbian lite.)

Unable to prepare setup for platform hass_opensprinkler.scene: Platform not found (No module named 'custom_components').

I had a pain getting this to work at all, as I had to put this into the components directory, as every time I tried to create a custom_components directory it wouldn't work.

I am also getting the following notifications:
The following components and platforms could not be set up:

hass_opensprinkler.binary_sensor
hass_opensprinkler.switch
hass_opensprinkler.sensor
hass_opensprinkler.scene
Please check your config.

I ended up having to put the hass_opensprinkler directory into the /srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/
 as putting it into the 
/srv/homeassistant/lib/python3.7/site-packages/homeassistant/custom_components/ 
never produced usable results.
What am I missing?

**Comment by vinteo** [comment]
hi @danielromney ,

It sounds like you have it in the wrong folder. It should it in your Home Assistant config folder (called `config` where your `configuration.yaml` sits:

`config/custom_components/hass_opensprinkler`

**Comment by danielromney** [comment]
There is no config folder in my set up for what ever reason. My path the my
configuration.yaml file is as follows.
/Home/homeassistant/. homeassistant/configuration.yaml

**Comment by danielromney** [comment]
I tried putting it in that folder, and never seemed to work. I'll try again
and let you know. I'll put it in,
/home/homeassistant/. homeassistant/custom_components/hass_opensprinkler

**Comment by danielromney** [comment]
Okay, it is now working. created the custom_components folder and placed the hass_opensprinkler folder in there and it worked.
