### ISSUE TITLE
Incorrect unavailable handling

### ISSUE THREAD

**Issue by bob-tm** [vinteo/hass-opensprinkler#293]
Hi,

I have regular blackouts and integration do not correctly handle it. 

![logbook](https://github.com/vinteo/hass-opensprinkler/assets/47008924/33b14a32-25f4-419a-8c70-b5f50edce8ac)
Let's look to an example
8.12.30 - blackout 
8.12.44 - it's unavailable  with "Timeout fetching OpenSprinkler resource status data" message. 
8.13.28 - it's alive with "Fetching OpenSprinkler resource status data recovered", but it's impossible. Still zero power. 
![log1](https://github.com/vinteo/hass-opensprinkler/assets/47008924/651e7854-4523-4af3-b5db-c802eb286531)

"Timeout fetching OpenSprinkler resource status data" it's very rare message. When I saw it - unavailable handled correctly.  But when there are: 
"Finished fetching OpenSprinkler resource status data in 10.003 seconds (success: False)",
"Cannot connect to controller",
everything is showed as "online"

Second strange thing: there is 10 sec timeouts with 5 seconds SCAN_INTERVAL.  Looks like it should be less than SCAN_INTERVAL. 
![log2](https://github.com/vinteo/hass-opensprinkler/assets/47008924/1cd232a8-36de-4152-996d-52ab5c084e12)
Another situation with "Fetching OpenSprinkler resource status data recovered" while there is total blackout

My current dirty solution - full reload OpenSprinkler integration on each blackout.

![log3](https://github.com/vinteo/hass-opensprinkler/assets/47008924/fe9f3d13-73ac-40aa-b0f7-f61a800fdc2d)
Now it's powered. Example in logs for short unavailable case. 
For this case I suggest count timeouts. For example if there is two continues timeouts - then change availability attribute or reset timeout counter.

**Comment by bob-tm** [comment]
Seems like reducing timeout from 10 sec to 3sec helps with unavailable  while blackout.

**Comment by functionpointer** [comment]
My OpenSprinkler got OOM killed. The integration remained mostly available, despite numerous errors:
```
Aug 01 09:40:00 netberry hass[418]: 2024-08-01 09:40:00.779 ERROR (MainThread) [custom_components.opensprinkler] Cannot connect to controller
Aug 01 09:40:05 netberry hass[418]: 2024-08-01 09:40:05.917 INFO (MainThread) [backoff] Backing off _request_http(...) for 0.1s (pyopensprinkler.OpenSprinklerConnectionError: Cannot connect to controller)
Aug 01 09:40:06 netberry hass[418]: 2024-08-01 09:40:06.031 INFO (MainThread) [backoff] Backing off _request_http(...) for 0.5s (pyopensprinkler.OpenSprinklerConnectionError: Cannot connect to controller)
Aug 01 09:40:06 netberry hass[418]: 2024-08-01 09:40:06.517 ERROR (MainThread) [backoff] Giving up _request_http(...) after 3 tries (pyopensprinkler.OpenSprinklerConnectionError: Cannot connect to controller)
Aug 01 09:40:06 netberry hass[418]: 2024-08-01 09:40:06.517 ERROR (MainThread) [custom_components.opensprinkler] Cannot connect to controller
Aug 01 09:40:10 netberry hass[418]: 2024-08-01 09:40:10.940 INFO (MainThread) [backoff] Backing off _request_http(...) for 0.9s (pyopensprinkler.OpenSprinklerConnectionError: Cannot connect to controller)
Aug 01 09:40:11 netberry hass[418]: 2024-08-01 09:40:11.889 INFO (MainThread) [backoff] Backing off _request_http(...) for 0.5s (pyopensprinkler.OpenSprinklerConnectionError: Cannot connect to controller)
Aug 01 09:40:12 netberry hass[418]: 2024-08-01 09:40:12.345 ERROR (MainThread) [backoff] Giving up _request_http(...) after 3 tries (pyopensprinkler.OpenSprinklerConnectionError: Cannot connect to controller)
Aug 01 09:40:12 netberry hass[418]: 2024-08-01 09:40:12.345 ERROR (MainThread) [custom_components.opensprinkler] Cannot connect to controller
Aug 01 09:40:16 netberry hass[418]: 2024-08-01 09:40:16.917 INFO (MainThread) [backoff] Backing off _request_http(...) for 0.5s (pyopensprinkler.OpenSprinklerConnectionError: Cannot connect to controller)
Aug 01 09:40:17 netberry hass[418]: 2024-08-01 09:40:17.453 INFO (MainThread) [backoff] Backing off _request_http(...) for 1.5s (pyopensprinkler.OpenSprinklerConnectionError: Cannot connect to controller)
```
![grafik](https://github.com/user-attachments/assets/3fae52a9-d6af-449a-b949-d97dd5b0c6aa)

This is bad because it defeats my monitoring system, which notifies me when something is "unavailable" for an extended period of time. This runs the risk of my plants not getting water, because i don't notice when OpenSprinkler fails!
