### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by doppiaemme** [vinteo/hass-opensprinkler#30]
Hi, 

I think I have followed carefoully the installatioon notes, however I am still struggling.
I've tried first manually then via HACS but still the same result.
I keep getting the following error:

`2019-09-29 20:49:00 ERROR (MainThread) [homeassistant.components.hassio] Component error: hass_opensprinkler - Integration hass_opensprinkler not found.`

The content seems correctly in the folder:
```
max@ubuntu-docker:~/hassio/homeassistant/custom_components/hass_opensprinkler$ ls
__init__.py  binary_sensor.py  manifest.json  scene.py  sensor.py  switch.py
```

and my config file includes:

```
hass_opensprinkler:
  host: 192.168.x.x
  password: xxxxxxx
```

ver 0.1.3
HA ver  0.99.3

anythin g obvious I am doing wrong????

thanks in advance!

2019-09-29 20:49:00 ERROR (MainThread) [homeassistant.components.hassio] Component error: hass_opensprinkler - Integration hass_opensprinkler not found.

**Comment by idxman01** [comment]
The setup generally looks fine.  Are the file permissions the same as other files under homeassistant?

**Comment by doppiaemme** [comment]
well I even installed it with HACS so it should se the permission correctly...
anyway, it seems they are all fine (other components work fine):

```
ls -l
total 16
drwxr-xr-x 4 root root 4096 Sep 29 11:14 alexa_media
drwxr-xr-x 3 root root 4096 Sep 28 00:00 gree
drwxr-xr-x 8 root root 4096 Sep 27 23:36 hacs
drwxr-xr-x 2 root root 4096 Sep 29 20:35 hass_opensprinkler
```

**Comment by vinteo** [comment]
Based on your description it looks fine. I just updated my home assistant to 0.99.3 to test and it worked fine for me as well. So I am out of ideas too :(

**Comment by doppiaemme** [comment]
It seems I managed to make it work, I guess something got corrupted as I initially tried to install it manually then via HACS.
How did it work?
Uninstall it from HACS, remove all the entry in the config file, reinstall it from HACS, re edit the config file.

thanks anyway!
