### ISSUE TITLE
UnicodeDecodeError - potentially related to OS upgrade 2.2.1

### ISSUE THREAD

**Issue by EricReiche** [vinteo/hass-opensprinkler#303]
Hi,

I'm receiving this error and the integration is refusing to connect:

> 2024-08-12 07:22:58.030 ERROR (MainThread) [custom_components.opensprinkler.config_flow] Unexpected exception
> Traceback (most recent call last):
>   File "/config/custom_components/opensprinkler/config_flow.py", line 64, in async_step_user
>     await controller.refresh()
>   File "/usr/local/lib/python3.12/site-packages/pyopensprinkler/__init__.py", line 229, in refresh
>     await self._refresh_state()
>   File "/usr/local/lib/python3.12/site-packages/pyopensprinkler/__init__.py", line 248, in _refresh_state
>     content = await self.request("/ja")
>               ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/pyopensprinkler/__init__.py", line 145, in request
>     content = await self._request_http(url)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/backoff/_async.py", line 151, in retry
>     ret = await target(*args, **kwargs)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/pyopensprinkler/__init__.py", line 202, in _request_http
>     content = await resp.json(
>               ^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 80, in json
>     return await super().json(*args, loads=loads, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1215, in json
>     return loads(stripped.decode(encoding))
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 1534: invalid start byte

I recently updated to https://github.com/OpenSprinkler/OpenSprinkler-Firmware/releases/tag/221(0) 
Home Assistant is on 2024.8.1
this Addon is on 1.3.7

**Comment by EricReiche** [comment]
Doesn't really look unusual to me, any other ideas?
```
➜  ~ curl -v http://192.168.20.184:8080/ja
*   Trying 192.168.20.184:8080...
* Connected to 192.168.20.184 (192.168.20.184) port 8080
> GET /ja HTTP/1.1
> Host: 192.168.20.184:8080
> User-Agent: curl/8.5.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 11
< Access-Control-Allow-Origin: *
< Cache-Control: max-age=0, no-cache, no-store, must-revalidate
< Connection: close
<
* Closing connection
{"fwv":221}#
```

**Comment by vinteo** [comment]
Besides upgrading the firmware did you update any station/programs names with special characters? Maybe charcters with accents?

**Comment by EricReiche** [comment]
Programs were a good tip!
Apparently the opensprinkler export/import process (required due to upgrade) can't handle German Umlauts in program names. I renamed the program and now it works fine.
Thanks for your help.

**Comment by EdLeckert** [comment]
> Doesn't really look unusual to me, any other ideas? Which request should I send to get the whole response to check that specific character at the position?
> 

You would have needed to add the password as an MD5 hash per the API manual.

Glad you figured it out. Perhaps we need to log an issue about the backup/restore with OS?
