### ISSUE TITLE
Rain Sensor in firmware 2.1.9

### ISSUE THREAD

**Issue by idxman01** [vinteo/hass-opensprinkler#31]
It appears that the rain sensor key was renamed from 'rs' to 'sn1' or 'sn2' in 2.1.9 due to supporting two sensors.  For now I've simply changed the key name, but will look at something more elegant time permitting if no one else adds a pull request.  eg: Check for sn1/sn2 to be a rain sensor then fall back to 'rs' if it's available.  Or maybe it should check the value of key 'fwv' via the '/jo' options call.

I'm sure this affects all versions of HA, though I'm running 0.99.3 at this time.

`In __init__.py`

```
    def rain_sensor(self):
    return self._get_controller_variable(CONF_RAIN_SENSOR, 'sn1')
```

**Comment by vinteo** [comment]
fixed in https://github.com/vinteo/hass-opensprinkler/pull/37
