### ISSUE TITLE
Delayed sensor setup on restart

### ISSUE THREAD

**Issue by Mattat01** [vinteo/hass-opensprinkler#38]
Hi,

Great work.

As expected, if OpenSprinker is down when Hassio starts up the entities are not set up and are not shown as available. However, Open Sprinkler always takes longer to restart than Hassio, so if there is a power failure I always need to reboot Hassio a while after to get the entities working.

Is there any way to delay the set-up of the entities so that they can be created after Open Sprinkler is running? I'm guessing the answer is no, but thought I'd ask!

Thanks,
Matthew

**Comment by vinteo** [comment]
Yea not sure that is possible. I also have a similar problem but luckily power failures are rare for me
