### ISSUE TITLE
input_number.<station name>_timer is unavailable 

### ISSUE THREAD

**Issue by devanl** [vinteo/hass-opensprinkler#42]
![4CE20FB2-B634-4FF8-89C3-F1C5849FFC49](https://user-images.githubusercontent.com/4000925/77866472-36507e00-7201-11ea-9ee6-c5667dbfd136.jpeg)

Station timer is unavailable for all stations and input is text-entry instead of slider.  Was working previously. 

Running 0.107.3

**Comment by martellucci** [comment]
same problem, I’ve got this error:

20-03-30 20:27:48 ERROR (MainThread) [supervisor.homeassistant] Error on call http://172.30.32.1:8123/api/states/binary_sensor.snapshots_stale: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]
20-03-30 20:27:48 ERROR (MainThread) [supervisor.api.proxy] Error on API for request states/binary_sensor.snapshots_stale

**Comment by vinteo** [comment]
Please take a look at the trouble shooting section in the README
