### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'state' - Troubleshooting guide not working

### ISSUE THREAD

**Issue by dandelor** [vinteo/hass-opensprinkler#49]
I'm using Ospi.

After installation with HACS on HASSIO **0.108.6** the switches do not work raising this error:

File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hass_opensprinkler/switch.py", line 89, in turn_on
    self._station.turn_on(int(float(mins.state)))
AttributeError: 'NoneType' object has no attribute 'state'

I added this in configuration file:
input_number:
   S01UlivoEViale_timer:
     min: 1
     max: 60
     step: 1
     mode: slider

But the log shows this error:
Invalid config for [input_number]: invalid slug S01UlivoEViale_timer (try s01ulivoeviale_timer) for dictionary value @ data['input_number']. Got OrderedDict([('S01UlivoEViale_timer', OrderedDict([('min', 1), ('max', 60), ('step', 1), ('mode', 'slider')]))]). (See /config/configuration.yaml, line 94). 

And does not solve the issue.

I also have this 
hass_opensprinkler:
  host: 192.168.1.XXXX
  password: dXXXXXXXXXXXXXX
  stations:
   - 0
   - 1
   - 2
   - 3

But it shows all the stations up to 8.

**Comment by vinteo** [comment]
did you try what the error log said?

```
Invalid config for [input_number]: invalid slug S01UlivoEViale_timer (try s01ulivoeviale_timer)
```

so with all lowercase
```yaml
input_number:
  s01ulivoeviale_timer:
    ...
```

**Comment by dandelor** [comment]
That  worked! Everything is fixed. I thought it automatically tried already the lower case option...

Thanks.

**Comment by vinteo** [comment]
Great :)
