### ISSUE TITLE
Multiple devices support

### ISSUE THREAD

**Issue by vinteo** [vinteo/hass-opensprinkler#6]
Allow for multiple OpenSprinkler devices

**Comment by wvella** [comment]
This would be a great feature! I have multiple opensprinklers in my property. Until this feature is released, is there a workaround available?

**Comment by vinteo** [comment]
if they are separate devices, you could make multiple copies of the component folder inside the `custom_components` folder ie `hass_opensprinkler2`, `hass_opensprinkler3`, etc and update this line to match it: 

https://github.com/vinteo/hass-opensprinkler/blob/master/custom_components/hass_opensprinkler/__init__.py#L11

Then use `hass_opensprinkler2` etc in the config. I haven't tested it so not 100% it would work but you could give it a shot.

Also I think multiple devices could be connected to together, if you have that setup not sure how that would work.

**Comment by sanbroz** [comment]
Yes, I have tested with 2 sprinklers, but you have to change hass_opensprinkler instances in all files

**Comment by nerodoxus** [comment]
Hi,

Maybe each instance could have an prefix attribute? It coud be added to all entities that are created during startup. 
Right now e.g. sensor.water_level is created that could interfere with existing sensor created before from other device.
