### ISSUE TITLE
Controller Discovery

### ISSUE THREAD

**Issue by travisghansen** [vinteo/hass-opensprinkler#75]
https://opensprinkler.com/faq/

It appears the app does network discovery of the controllers...should we research that and integrate it?

**Comment by idxman01** [comment]
FWIW, I'd put this lower on the list as it's probably a one-time change for most.  I don't believe discovery ever worked for me anyway since it's on a different vlan.

**Comment by travisghansen** [comment]
Yeah, I agree on this one. Something I read said it was doing a brute-force scan anyway so I'm not in favor of that myself.

**Comment by vinteo** [comment]
Thinking about it I don't think this really brings much value, plus will definitely not want to do a brute scan method.

**Comment by travisghansen** [comment]
Agreed!
