### ISSUE TITLE
Add station sensors as disabled if is station is disabled

### ISSUE THREAD

**Issue by vinteo** [vinteo/hass-opensprinkler#77]
- ~~don't add station  entities if station is disabled~~ Add station sensors as disabled if is station is disabled
- ~~remove station switches~~

**Comment by travisghansen** [comment]
@vinteo yeah, `station.enabled` is what you're after. Not sure about adding the sensor in a disabled state though...

**Comment by vinteo** [comment]
`station.enabled` can refer to a disabled station that is connected. I am talking about a station pot that is not connected. 

For example I have a very simple setup of 4 out of 8 stations but it will always add sensors and switches for 8 stations even though the other 4 don't exist. It uses the default names like S05, S06 etc.  I want to not have those sensors and switches if possible. Unfortunately it doesn't look it it is possible to distinguish except looking at the default name which is really hacky.

**Comment by travisghansen** [comment]
Not sure what you mean by connected here. That's the point of disabling stations is so they don't show up in the upstream UI even..makes sense here if we want to do it.

**Comment by vinteo** [comment]
As in the controller supports 8 stations but I only have 4 physically connected/wired.

The station switch (in HA) is for enabling/disabling stations. If we go that way we should remove the switches or a restart of HA will remove the a switch after it is disabled.

Its not a big deal though, just thought it would be a nice to have, usually just don't include those sensors/switches in my HA UI

**Comment by travisghansen** [comment]
Yeah, maybe we have different understanding of what/how the disabled stations are used.

I look at them as a relatively permanent thing like your scenario...I have 8 ports and only use 4 (or whatever). In my case I have 24 but use 16.

If we had a configuration option to 'ignore' disabled stations we'd probably apply the logic to any/all station entities (switches, sensors, etc).

Hypothetically the same thought could be applied to the programs as well. Although disabled programs (for testing) are more likely to be used than disabled stations (at least seems that way on the surface).

**Comment by Nick-Adams-AU** [comment]
IMHO, disabled stations shouldn't show in HASS. This would obviously remove the need for functionality to enable or disable zones - this should be managed through OpenSprinkler app.

**Comment by travisghansen** [comment]
So default to that logic then?

```python
if not station.enabled:
    add_entity_as_disabled
```

We'd need that logic across all the different types (switches, binary, etc) right?

**Comment by Nick-Adams-AU** [comment]
I'm struggling to understand why adding an unconfigured/disabled zone to HASS would be useful. If/when you do configure and enable the zone using the OS app, it can be added to HASS.

**Comment by travisghansen** [comment]
Could be done that way. You'd have to restart HASS vs going and finding the entity and enabling it. I don't see any harm in adding it but either way..

**Comment by vinteo** [comment]
The only thing I can think of is if the user wants to enable/disable stations with automations on HA.  But ignoring disabled stations fits my use case so I am not fussed. So the station switches will also be removed.

**Comment by vinteo** [comment]
updated title and description

**Comment by travisghansen** [comment]
@vinteo we should make this don't add *any* station entities (sensors, switches, etc) right?

**Comment by vinteo** [comment]
yes, there wouldn't be any station switches at all since the switch is to enable/disable, I don't think it makes sense to keep them, even if the station is enabled? Besides that we only have binary sensors and sensors which are both sensors haha. But changed to entities

**Comment by travisghansen** [comment]
I guess everything hinges on whether we can add in a disabled state, or if you plan on ignoring altogether.

**Comment by vinteo** [comment]
even if we add the entities as disabled, I don't think switches make sense, since turning the switch off will disable the switch entity itself (after restart). Seems counter intuitive

**Comment by travisghansen** [comment]
I'm not entirely sure about that..does the setting restore the user's selection as set in the 'db'?

**Comment by vinteo** [comment]
Not sure what you mean, I guess we can just play around with it and see how it behaves

**Comment by travisghansen** [comment]
Going to go read up on it a bit and test the behavior..

**Comment by travisghansen** [comment]
https://developers.home-assistant.io/docs/entity_registry_disabled_by/

**Comment by travisghansen** [comment]
This is the kind of thing that concerns me about not making switches and adding entities for all programs/stations: #41

**Comment by travisghansen** [comment]
I'll also make the case that using `auto-entities` with the massive list of `state attributes` we have currently should make it pretty easy to create cards which filter on any kind of logic (enabled/disabled, etc, etc) relatively easily.

**Comment by vinteo** [comment]
The program switches will definitely stay, this was only for stations.

Honestly I can;t see a use case for the station switch at the moment, The current integration does not have this functionality and it was never requested (only for programs). If it was just for me I would remove the station switches all together. Just because it can be added doesn't mean we have to.

For the context of this PR, I think I will look into adding just the sensors as disabled if the station is disabled. Will keep the switches just there for now.

**Comment by travisghansen** [comment]
I like that. We need to find out if changing the disable/enabled default of an entity *afer creation* takes effect as we hope/expect.

**Comment by travisghansen** [comment]
I do think there's a case for station switches...they can be disabled (in OS) on a case by case basis to alter program runs. Say you create a program P1 and have 3 stations set to execute, but every other day you want to remove 1 of them from the rotation you can simply disable the station and P1 will run without it. Some may say just create another program, and that's possibly valid but options are good :)

I'm interested in what the numbers will be for the integration after full inclusion into hass proper. The general user base may go up a bit if it's readily available and part of core.

**Comment by travisghansen** [comment]
Actually, I changed my mind on this (doesn't mean you can't do it). I think they should stay. For the use-case above where someone is flipping stations on/off through automation etc this leaves them at the whims of the current state at startup time. My vote is to leave it as is and let folks disable as desired using hass directly.

**Comment by vinteo** [comment]
Just because it can be done in another way doesn't mean it should. OS is quite a powerful device with so many options, it should be taken advantage of. If you provide an alternative they might take that route even though a viable option is available to them

Of course I am not gonna tell people not do it in the way they want so we can consider it if it is requested but all this is just speculation at the moment, IMO we should keep things simple and only add the stuff we know can be useful and add to it later. If we try and add everything it means more things that could potentially break so it just useless effort for us to maintain if it not being used. 

Which is why I am seriously considering removing the station switches for 1.0. We can easily add them in if people want it. ATM neither you or I or the current integration users (s it didn't exist before) use it. 

As for the disabled states for sensors, I don't plan on adding this for 1.0.

**Comment by travisghansen** [comment]
I think it’s actually *more* complex to have altering behavior. I’m against removing either :) I think basic on/off functionality makes sense for all 3 things (controller, programs, stations). If folks don’t want to see them they can follow the established hass pattern of disabling the entity using hass thereby keeping the logic out of the integration completely.

**Comment by Nick-Adams-AU** [comment]
> I do think there's a case for station switches...they can be disabled (in OS) on a case by case basis to alter program runs. Say you create a program P1 and have 3 stations set to execute, but every other day you want to remove 1 of them from the rotation you can simply disable the station and P1 will run without it. Some may say just create another program, and that's possibly valid but options are good :)

I hadn't considered that someone might want to disable (and eventually, re-enable) a configured zone. My use-case is that all configured zones are active and I use programs to choose which to run.

In the spirit of changing positions, I think the switches should stay. People can disable any entities they don't want.

**Comment by travisghansen** [comment]
Lovely day! :) we’re super close!

**Comment by vinteo** [comment]
I think its worse for the user experience to add something and remove it later which is why I was thinking of removing station switches before release. And add them in later when/if needed. But seems like the consensus is to keep them

And I totally agree with the point of letting the user disable the entities that they don't want, I was just questioning if they should be there in the first place, in the case of the station switches. 

This PR was opened to consider disabling sensors for disabled stations by default (so user can always enable them after). But after reading the docs again just now it seems like it does not do what I thought, the entities are not created by default (haven't tested yet) so maybe we can't do what I want in terms of the sensors.

**Comment by travisghansen** [comment]
It was good to think through it all. It’s tied to the switch conversation as it’s directly connected to the switch logic..meaning if we keep the use-case of stations going on off it pretty much answers this question as well IMO.
