### ISSUE TITLE
Add binary sensor for rain sensor

### ISSUE THREAD

**Issue by Nick-Adams-AU** [vinteo/hass-opensprinkler#82]
As per https://github.com/vinteo/hass-opensprinkler/pull/52#issuecomment-636035023, add binary sensors for each of the sensors. We probably need to exclude this if Sensor 1 is a flow sensor.

**Comment by travisghansen** [comment]
Can you review the properties here and propose a full list if desired sensors?

- https://github.com/vinteo/py-opensprinkler/blob/master/pyopensprinkler/__init__.py

**Comment by Nick-Adams-AU** [comment]
Here's my thoughts:

last_run_*
rain_delay_active
rain_sensor_active
sensor_1_*
sensor_2_*
flow_rate

**Comment by travisghansen** [comment]
I'll review in a bit..

**Comment by travisghansen** [comment]
@Nick-Adams-AU ok, I think it only makes sense to add the following:

- `sensor_{1,2}_active` (binary)
- `flow_rate` (sensor)
- `rain_delay_active` (binary)

**Comment by travisghansen** [comment]
@vinteo any issues with the above?

**Comment by vinteo** [comment]
Looks good

**Comment by travisghansen** [comment]
I’ll work on these.

**Comment by Nick-Adams-AU** [comment]
Is it worth mapping the rain sensor status to Wet/Dry ?

**Comment by vinteo** [comment]
I think we can set the device class to `moisture`

**Comment by vinteo** [comment]
are we missing `rain_sensor_active`?

**Comment by Nick-Adams-AU** [comment]
Ahh...it does look like it is missing. I guess it is a derivative of the binary_sensor.opensprinkler_sensor_X_active...depending on your config.

**Comment by travisghansen** [comment]
@Nick-Adams-AU I believe you are right...at least that's how I understood things. If we want to support older controller/firmware versions then we'll need to adjust that bit..

**Comment by vinteo** [comment]
oh that's a deprecated thing? in that case let's not add it

**Comment by travisghansen** [comment]
@vinteo currently a couple properties exist in the library that are for older versions I believe as well. If we don't want to support those we should probably rip them out of there and just make the baseline be 2.1.9?

**Comment by vinteo** [comment]
@travisghansen please take a look at https://github.com/vinteo/py-opensprinkler/pull/26

**Comment by travisghansen** [comment]
Merged.

**Comment by travisghansen** [comment]
@vinteo anything left on this one or should we close?

**Comment by vinteo** [comment]
closing
