### ISSUE TITLE
Add service to stop all stations

### ISSUE THREAD

**Issue by vinteo** [vinteo/hass-opensprinkler#84]
run on controller entities

**Comment by travisghansen** [comment]
For ease of use does it make any sense to make it available to any entity?

**Comment by vinteo** [comment]
definitely makes it easier but not sure we should

**Comment by travisghansen** [comment]
Agreed.

**Comment by travisghansen** [comment]
Do the method names on the objects have to match exactly what the service name is called? I've not wrapped my brain around the binding here yet..

**Comment by vinteo** [comment]
the method name is the third param (string) of register service method. I think should be `stop_all` for this case

**Comment by travisghansen** [comment]
Ok cool. Go ahead on this one similar to the other I suppose using the inheritance stuff.
