### ISSUE TITLE
SCAN_INTERVAL user option

### ISSUE THREAD

**Issue by travisghansen** [vinteo/hass-opensprinkler#88]
Forgot to create this beforehand :( I think it's good to change the default to `5` like the OS UI and also allow it to be configurable by the user.

**Comment by vinteo** [comment]
TBH, I don't think this is very useful now that the integration is working relatively well at 5 seconds.

**Comment by travisghansen** [comment]
Probably would just add it to be consistent with many of the other integrations, but not critical.

**Comment by vinteo** [comment]
Interestingly 2021.6 has a new feature to disable polling for each integration and do manual updates via a service call. An advanced user feature for sure, but technically the user can now determine their own polling.
