### ISSUE TITLE
Last run sensor time seems to be off due to timezones

### ISSUE THREAD

**Issue by vinteo** [vinteo/hass-opensprinkler#89]
For me something seems off with the timestamp for the last run sensor.

**Comment by Nick-Adams-AU** [comment]
Can confirm - it looks like it is out by the entire timezone difference.

I'm seeing `2020-05-31T08:10:01+00:00` which looks like a UTC timestamp (`+00:00`) but the correct timestamp should actually read `2020-05-31T08:10:01+10:00`.

**Comment by travisghansen** [comment]
For the state attributes I used the same thing that was already there for this sensor so I'm guessing those are off as well?

**Comment by travisghansen** [comment]
How are you running `hass`? I’m running with the official docker images and setting the timezone properly and the time is correct for the value for me.

**Comment by travisghansen** [comment]
Scratch that, it’s off for me as well. Was looking at the wrong thing.

**Comment by travisghansen** [comment]
Oh boy, OS is providing the wrong value :( They are providing the timestamp of the 'time' but when it was that time in utc.  For example, in my timezone the last run with 8:40 p.m., the value returned is the timestamp for 8:40 p.m. in UTC 

Crazy town.

**Comment by Nick-Adams-AU** [comment]
Did you open a bug for this with OS? I had a quick look but couldn't find anything.

**Comment by travisghansen** [comment]
I didn’t no :(

**Comment by PeteBa** [comment]
The OS api for this is a bit odd i.e. the docs says **"devt: Device time (epoch time). This is always the local time"**. Epoch time is delta from `1970-01-01T00:00:00Z` so UTC but the api then states that it is in local time which is confusing. The OS code confirms this:

``` c++
time_t OpenSprinkler::now_tz() {
	return now()+(int32_t)3600/4*(int32_t)(iopts[IOPT_TIMEZONE]-48);
}
```

**Comment by travisghansen** [comment]
Time is always fun... the behavior seems really odd to me though.

**Comment by Nick-Adams-AU** [comment]
There seems to be a misunderstanding as to what unix timestamps actually represent.

Either way, the now() + timezone offset is incorrect. For me, it shows a timestamp in the future and OS isn't responsible for time travel...yet?!

**Comment by travisghansen** [comment]
@Nick-Adams-AU I agree 100% with the assessment. As mentioned above, for me the value of the time recorded is the same 'time' (9:00 a.m. for example) of day as my time zone but stored as whatever timestamp that same 'time' of day is in UTC (9:00 a.m.).

**Comment by vinteo** [comment]
all the other timestamps seem to be epoch utc too, I wonder why they decide to make this different. The OS API does provide the time zone setting (in another weird format ... `Time zone (floating point time zone value * 4 + 48). For example, GMT+0:00 is 48; GMT-4:00 is 32, GMT+9:30 is 86. Acceptable range is 0 to 108.`) so technically we can use that to convert it.

**Comment by travisghansen** [comment]
Should we just convert to the timezone of the HA install? Probably pretty easy to do that..

**Comment by vinteo** [comment]
That's with the assumption that both HA and OS are set to the same timezone, so technically is not correct, but it might be an easy way out for now.

**Comment by travisghansen** [comment]
Right. My thoughts exactly.

**Comment by PeteBa** [comment]
> The OS API does provide the time zone setting (in another weird format ... `Time zone (floating point time zone value * 4 + 48). For example, GMT+0:00 is 48; GMT-4:00 is 32, GMT+9:30 is 86. Acceptable range is 0 to 108.`) so technically we can use that to convert it.

The reason behind the timezone encoding was to store the offset in a single byte. Early OS devices were memory constrained and every byte counted.

Sampling the code, time based api parameters are derived from `now_tz()` but given that the api also returns `tz` then you could calculate UTC equivalent and leave to HA UI for presentation.

**Comment by vinteo** [comment]
Yea that would be the ideal solution with what we currently have. I think `pyopensprinkler` should do the conversion and return the result the `last_run` as epoch time (in utc). Then nothing needs to be done here.
