### ISSUE TITLE
Slack Workspace

### ISSUE THREAD

**Issue by vinteo** [vinteo/hass-opensprinkler#94]
I created a Slack workspace for additional discussions and help with collaboration. Use this link to join:

https://join.slack.com/t/opensprinkler-ints/shared_invite/zt-exuhv4f5-SQbp7ACyLiSYaPXinkFG1Q

**Comment by vinteo** [comment]
Just closing this so its not on the open list now that I have it pinned

**Comment by nagyrobi** [comment]
The link is dead

**Comment by vinteo** [comment]
Link updated
